print("this is \\\\ double backslash")
print("this is /\\/\\/\\/\\/\\ mounatain")
print("he is \t awesome(use escape sequence instead of manual spaces")
print("\\\" \\n \\t \\\'",end=" ")
print("(print this as an output)")